<a href="https://colab.research.google.com/github/Datascientist2004/Datascientist2004/blob/main/dataanalysts1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

b = np.empty(2, dtype = int)
print("Matrix b : \n", b)

a = np.empty([2, 2], dtype = int)
print("\nMatrix a : \n", a)
 c = np.empty([3, 3])
print("\nMatrix c : \n", c)

IndentationError: unexpected indent (<ipython-input-1-df732c7a844a>, line 8)

In [1]:
import numpy as np

b = np.empty(2, dtype = int)
print("Matrix b : \n", b)

a = np.empty([2, 2], dtype = int)
print("\nMatrix a : \n", a)

# Fix the indentation of this line
c = np.empty([3, 3])
print("\nMatrix c : \n", c)

Matrix b : 
 [-4611686018427387904      140733726687231]

Matrix a : 
 [[101934016565972               0]
 [              0               0]]

Matrix c : 
 [[5.03620954e-310 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [2]:
import numpy as np

# Sample Data
arr = [5, 6, 11]

# Mean
mean = np.mean(arr)

print("Mean = ", mean)


Mean =  7.333333333333333


In [3]:
from scipy import stats

# sample Data
arr = [1, 2, 2, 3]

# Mode
mode = stats.mode(arr)
print("Mode = ", mode)


Mode =  ModeResult(mode=2, count=2)


In [4]:
import numpy as np

# sample Data
arr = [1, 2, 3, 4]

# Median
median = np.median(arr)

print("Median = ", median)


Median =  2.5


In [5]:
import numpy as np

# Sample Data
arr = [1, 2, 3, 4, 5]

# Finding Max
Maximum = max(arr)
# Finding Min
Minimum = min(arr)

# Difference Of Max and Min
Range = Maximum-Minimum
print("Maximum = {}, Minimum = {} and Range = {}".format(
	Maximum, Minimum, Range))


Maximum = 5, Minimum = 1 and Range = 4


In [6]:
import statistics

# sample data
arr = [1, 2, 3, 4, 5]
# variance
print("Var = ", (statistics.variance(arr)))


Var =  2.5


In [7]:
import statistics

# sample data
arr = [1, 2, 3, 4, 5]

# Standard Deviation
print("Std = ", (statistics.stdev(arr)))


Std =  1.5811388300841898


In [8]:
# Import pandas package
import pandas as pd

# Assign data
data = {'Name': ['Jai', 'Princi', 'Gaurav',
				'Anuj', 'Ravi', 'Natasha', 'Riya'],
		'Age': [17, 17, 18, 17, 18, 17, 17],
		'Gender': ['M', 'F', 'M', 'M', 'M', 'F', 'F'],
		'Marks': [90, 76, 'NaN', 74, 65, 'NaN', 71]}

# Convert into DataFrame
df = pd.DataFrame(data)

# Display data
df


Name  Age Gender Marks
0      Jai   17      M    90
1   Princi   17      F    76
2   Gaurav   18      M   NaN
3     Anuj   17      M    74
4     Ravi   18      M    65
5  Natasha   17      F   NaN
6     Riya   17      F    71

from matplotlib import pyplot as plt
df['Age'].plot(kind='hist', bins=20, title='Age')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
df.groupby('Name').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
df.groupby('Gender').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
df.groupby('Marks').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df['Age'].plot(kind='line', figsize=(8, 4), title='Age')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Gender'].value_counts()
    for x_label, grp in df.groupby('Name')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Name')
_ = plt.ylabel('Gender')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Marks'].value_counts()
    for x_label, grp in df.groupby('Gender')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Gender')
_ = plt.ylabel('Marks')

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(df['Name'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df, x='Age', y='Name', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(df['Gender'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df, x='Age', y='Gender', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(df['Marks'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df, x='Age', y='Marks', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [9]:
# Compute average
c = avg = 0
for ele in df['Marks']:
	if str(ele).isnumeric():
		c += 1
		avg += ele
avg /= c

# Replace missing values
df = df.replace(to_replace="NaN",
				value=avg)

# Display data
df


Name  Age Gender  Marks
0      Jai   17      M   90.0
1   Princi   17      F   76.0
2   Gaurav   18      M   75.2
3     Anuj   17      M   74.0
4     Ravi   18      M   65.0
5  Natasha   17      F   75.2
6     Riya   17      F   71.0

In [10]:
# Categorize gender
df['Gender'] = df['Gender'].map({'M': 0,
								'F': 1, }).astype(float)

# Display data
df


Name  Age  Gender  Marks
0      Jai   17     0.0   90.0
1   Princi   17     1.0   76.0
2   Gaurav   18     0.0   75.2
3     Anuj   17     0.0   74.0
4     Ravi   18     0.0   65.0
5  Natasha   17     1.0   75.2
6     Riya   17     1.0   71.0

In [11]:
# Filter top scoring students
df = df[df['Marks'] >= 75].copy()

# Remove age column from filtered DataFrame
df.drop('Age', axis=1, inplace=True)

# Display data
df


Name  Gender  Marks
0      Jai     0.0   90.0
1   Princi     1.0   76.0
2   Gaurav     0.0   75.2
5  Natasha     1.0   75.2

In [12]:
# import module
import pandas as pd

# creating DataFrame for Student Details
details = pd.DataFrame({
	'ID': [101, 102, 103, 104, 105, 106,
		107, 108, 109, 110],
	'NAME': ['Jagroop', 'Praveen', 'Harjot',
			'Pooja', 'Rahul', 'Nikita',
			'Saurabh', 'Ayush', 'Dolly', "Mohit"],
	'BRANCH': ['CSE', 'CSE', 'CSE', 'CSE', 'CSE',
			'CSE', 'CSE', 'CSE', 'CSE', 'CSE']})

# printing details
print(details)


    ID     NAME BRANCH
0  101  Jagroop    CSE
1  102  Praveen    CSE
2  103   Harjot    CSE
3  104    Pooja    CSE
4  105    Rahul    CSE
5  106   Nikita    CSE
6  107  Saurabh    CSE
7  108    Ayush    CSE
8  109    Dolly    CSE
9  110    Mohit    CSE


In [13]:
# Import module
import pandas as pd

# Creating Dataframe for Fees_Status
fees_status = pd.DataFrame(
	{'ID': [101, 102, 103, 104, 105,
			106, 107, 108, 109, 110],
	'PENDING': ['5000', '250', 'NIL',
				'9000', '15000', 'NIL',
				'4500', '1800', '250', 'NIL']})

# Printing fees_status
print(fees_status)


    ID PENDING
0  101    5000
1  102     250
2  103     NIL
3  104    9000
4  105   15000
5  106     NIL
6  107    4500
7  108    1800
8  109     250
9  110     NIL


In [14]:
# Import module
import pandas as pd

# Creating Dataframe
details = pd.DataFrame({
	'ID': [101, 102, 103, 104, 105,
		106, 107, 108, 109, 110],
	'NAME': ['Jagroop', 'Praveen', 'Harjot',
			'Pooja', 'Rahul', 'Nikita',
			'Saurabh', 'Ayush', 'Dolly', "Mohit"],
	'BRANCH': ['CSE', 'CSE', 'CSE', 'CSE', 'CSE',
			'CSE', 'CSE', 'CSE', 'CSE', 'CSE']})

# Creating Dataframe
fees_status = pd.DataFrame(
	{'ID': [101, 102, 103, 104, 105,
			106, 107, 108, 109, 110],
	'PENDING': ['5000', '250', 'NIL',
				'9000', '15000', 'NIL',
				'4500', '1800', '250', 'NIL']})

# Merging Dataframe
print(pd.merge(details, fees_status, on='ID'))


    ID     NAME BRANCH PENDING
0  101  Jagroop    CSE    5000
1  102  Praveen    CSE     250
2  103   Harjot    CSE     NIL
3  104    Pooja    CSE    9000
4  105    Rahul    CSE   15000
5  106   Nikita    CSE     NIL
6  107  Saurabh    CSE    4500
7  108    Ayush    CSE    1800
8  109    Dolly    CSE     250
9  110    Mohit    CSE     NIL


In [15]:
# Import module
import pandas as pd

# Creating Data
car_selling_data = {'Brand': ['Maruti', 'Maruti', 'Maruti',
							'Maruti', 'Hyundai', 'Hyundai',
							'Toyota', 'Mahindra', 'Mahindra',
							'Ford', 'Toyota', 'Ford'],
					'Year': [2010, 2011, 2009, 2013,
							2010, 2011, 2011, 2010,
							2013, 2010, 2010, 2011],
					'Sold': [6, 7, 9, 8, 3, 5,
							2, 8, 7, 2, 4, 2]}

# Creating Dataframe of car_selling_data
df = pd.DataFrame(car_selling_data)

# printing Dataframe
print(df)


       Brand  Year  Sold
0     Maruti  2010     6
1     Maruti  2011     7
2     Maruti  2009     9
3     Maruti  2013     8
4    Hyundai  2010     3
5    Hyundai  2011     5
6     Toyota  2011     2
7   Mahindra  2010     8
8   Mahindra  2013     7
9       Ford  2010     2
10    Toyota  2010     4
11      Ford  2011     2


In [16]:
# Import module
import pandas as pd

# Creating Data
car_selling_data = {'Brand': ['Maruti', 'Maruti', 'Maruti',
							'Maruti', 'Hyundai', 'Hyundai',
							'Toyota', 'Mahindra', 'Mahindra',
							'Ford', 'Toyota', 'Ford'],
					'Year': [2010, 2011, 2009, 2013,
							2010, 2011, 2011, 2010,
							2013, 2010, 2010, 2011],
					'Sold': [6, 7, 9, 8, 3, 5,
							2, 8, 7, 2, 4, 2]}

# Creating Dataframe for Provided Data
df = pd.DataFrame(car_selling_data)

# Group the data when year = 2010
grouped = df.groupby('Year')
print(grouped.get_group(2010))


       Brand  Year  Sold
0     Maruti  2010     6
4    Hyundai  2010     3
7   Mahindra  2010     8
9       Ford  2010     2
10    Toyota  2010     4


In [17]:
# Import module
import pandas as pd

# Initializing Data
student_data = {'Name': ['Amit', 'Praveen', 'Jagroop',
						'Rahul', 'Vishal', 'Suraj',
						'Rishab', 'Satyapal', 'Amit',
						'Rahul', 'Praveen', 'Amit'],

				'Roll_no': [23, 54, 29, 36, 59, 38,
							12, 45, 34, 36, 54, 23],

				'Email': ['xxxx@gmail.com', 'xxxxxx@gmail.com',
						'xxxxxx@gmail.com', 'xx@gmail.com',
						'xxxx@gmail.com', 'xxxxx@gmail.com',
						'xxxxx@gmail.com', 'xxxxx@gmail.com',
						'xxxxx@gmail.com', 'xxxxxx@gmail.com',
						'xxxxxxxxxx@gmail.com', 'xxxxxxxxxx@gmail.com']}

# Creating Dataframe of Data
df = pd.DataFrame(student_data)

# Printing Dataframe
print(df)


        Name  Roll_no                 Email
0       Amit       23        xxxx@gmail.com
1    Praveen       54      xxxxxx@gmail.com
2    Jagroop       29      xxxxxx@gmail.com
3      Rahul       36          xx@gmail.com
4     Vishal       59        xxxx@gmail.com
5      Suraj       38       xxxxx@gmail.com
6     Rishab       12       xxxxx@gmail.com
7   Satyapal       45       xxxxx@gmail.com
8       Amit       34       xxxxx@gmail.com
9      Rahul       36      xxxxxx@gmail.com
10   Praveen       54  xxxxxxxxxx@gmail.com
11      Amit       23  xxxxxxxxxx@gmail.com


In [24]:
# import module
import pandas as pd

# initializing Data
student_data = {'Name': ['Amit', 'Praveen', 'Jagroop',
						'Rahul', 'Vishal', 'Suraj',
						'Rishab', 'Satyapal', 'Amit',
						'Rahul', 'Praveen', 'Amit'],

				'Roll_no': [23, 54, 29, 36, 59, 38,
							12, 45, 34, 36, 54, 23],
				'Email': ['xxxx@gmail.com', 'xxxxxx@gmail.com',
						'xxxxxx@gmail.com', 'xx@gmail.com',
						'xxxx@gmail.com', 'xxxxx@gmail.com',
						'xxxxx@gmail.com', 'xxxxx@gmail.com',
						'xxxxx@gmail.com', 'xxxxxx@gmail.com',
						'xxxxxxxxxx@gmail.com', 'xxxxxxxxxx@gmail.com']}

# creating dataframe
df = pd.DataFrame(student_data)

# Here df.duplicated() list duplicate Entries in ROllno.
# So that ~(NOT) is placed in order to get non duplicate values.
non_duplicate = df[~df.duplicated('Roll_no')]

# printing non-duplicate values
print(non_duplicate)


       Name  Roll_no             Email
0      Amit       23    xxxx@gmail.com
1   Praveen       54  xxxxxx@gmail.com
2   Jagroop       29  xxxxxx@gmail.com
3     Rahul       36      xx@gmail.com
4    Vishal       59    xxxx@gmail.com
5     Suraj       38   xxxxx@gmail.com
6    Rishab       12   xxxxx@gmail.com
7  Satyapal       45   xxxxx@gmail.com
8      Amit       34   xxxxx@gmail.com


In [25]:
# importing pandas module
import pandas as pd

# Define a dictionary containing employee data
data1 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
		'Age':[27, 24, 22, 32],
		'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
		'Qualification':['Msc', 'MA', 'MCA', 'Phd'],
		'Mobile No': [97, 91, 58, 76]}

# Define a dictionary containing employee data
data2 = {'Name':['Gaurav', 'Anuj', 'Dhiraj', 'Hitesh'],
		'Age':[22, 32, 12, 52],
		'Address':['Allahabad', 'Kannuaj', 'Allahabad', 'Kannuaj'],
		'Qualification':['MCA', 'Phd', 'Bcom', 'B.hons'],
		'Salary':[1000, 2000, 3000, 4000]}

# Convert the dictionary into DataFrame
df = pd.DataFrame(data1,index=[0, 1, 2, 3])

# Convert the dictionary into DataFrame
df1 = pd.DataFrame(data2, index=[2, 3, 6, 7])


In [26]:
res = pd.concat([df, df1])
